// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalSite.Persistence;

namespace PersonalSite.Persistence.Migrations
{
    [DbContext(typeof(PersonalSiteDbContext))]
    partial class PersonalSiteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PersonalSite.Domain.Entities.JobExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TechStack")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("JobExperiences");
                });

            modelBuilder.Entity("PersonalSite.Domain.Entities.JobExperience", b =>
                {
                    b.OwnsOne("PersonalSite.Domain.ValueObjects.JobPeriod", "JobPeriod", b1 =>
                        {
                            b1.Property<int>("JobExperienceId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("End")
                                .HasColumnType("datetime(6)");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("JobExperienceId");

                            b1.ToTable("JobExperiences");

                            b1.WithOwner()
                                .HasForeignKey("JobExperienceId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
