version: "3"

services: 
  postgresql:
    image: postgres:14.1
    container_name: personal_site_postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
